package com.wut.cars.model;

import java.io.Serializable;

/**
 * User モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** userid. */
	private String userid;

	/** password. */
	private String password;

	/** birthday. */
	private String birthday;

	/** personalid. */
	private String personalid;

	/** email. */
	private String email;

	/**
	 * コンストラクタ.
	 */
	public User() {
	}

	/**
	 * userid を設定します.
	 * 
	 * @param userid
	 *            userid
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * userid を取得します.
	 * 
	 * @return userid
	 */
	public String getUserid() {
		return this.userid;
	}

	/**
	 * password を設定します.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * password を取得します.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * birthday を設定します.
	 * 
	 * @param birthday
	 *            birthday
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/**
	 * birthday を取得します.
	 * 
	 * @return birthday
	 */
	public String getBirthday() {
		return this.birthday;
	}

	/**
	 * personalid を設定します.
	 * 
	 * @param personalid
	 *            personalid
	 */
	public void setPersonalid(String personalid) {
		this.personalid = personalid;
	}

	/**
	 * personalid を取得します.
	 * 
	 * @return personalid
	 */
	public String getPersonalid() {
		return this.personalid;
	}

	/**
	 * email を設定します.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * email を取得します.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}


}
